name: Report a bug
description: Tell us about a bug or issue you may have identified on the Modus Docs theme.
title: "Provide a general summary of the issue"
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Provide a summary of the issue and what you expected to happen, including specific steps to reproduce.
    validations:
      required: true
