name: Lint Code Base

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:
    branches-ignore:
      - "dependabot/**"

jobs:
  build:
    permissions:
      contents: read #  to fetch code (actions/checkout)
      statuses: write #  to mark status of each linter run (super-linter/super-linter/slim)

    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: .*css/.*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: true
          JAVASCRIPT_DEFAULT_STYLE: prettier
          LINTER_RULES_PATH: /
          LOG_LEVEL: NOTICE
          SUPPRESS_POSSUM: true
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CHECKOV: false
          VALIDATE_EDITORCONFIG: false
          VALIDATE_HTML: false
          VALIDATE_JSCPD: false
          VALIDATE_MARKDOWN: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_XML: false
